export const dziczSpotkania = {
  type: "picker",
  list: [
    "Błędne ogniki prowadzą na śmierć",
"Drużyna zabłądziła na losowe pole przyległe do docelowego",
"Frywolne duszki szukają rozrywki",
"Goniec wiezie ważne wieści",
"Maruderzy szukają łatwych ofiar",
"Myśliwy tropi groźnego potwora",
"Negocjujące sekty – obie szukają wiernych",
"Niespokojne duchy szukają ukojenia",
"Okultyści odprawiają rytuał",
"Partyzanci przygotowują zasadzkę",
"Plądrowana osada – zarówno zbójcy, jak i ofiary przyjmą wsparcie",
"Potwór atakuje każdego w zasięgu wzroku",
"Potwór z młodymi broni potomstwa",
"Pustelnik szuka odosobnienia",
"Sprzeczający się przyjaciele – obaj szukają poparcia",
"Uchodźcy szukają pomocy w przeprawie",
"Walczące oddziały – oba szukają wsparcia",
"Zielarz szuka rzadkich ziół",
"Zwiadowcy starają się przemknąć niepostrzeżenie",
"Żołnierz szuka pomocy medycznej", 
  ],
};

export const dziczSpotkaniaNaRzece = {
  type: "picker",
  list: ["Bobry budują tamę",
  "Drwale spławiają drewno",
  "Flisacy naprawiają tratwę",
  "Kapłani dokonują rytualnych ablucji",
  "Mielizna nieoznaczona na mapach",
  "Potwór wynurza się z głębin",
  "Robotnicy budują most",
  "Wędkarz przysnął na brzegu",
  "Wędrowiec tonie",
  "Wodospad nieoznaczony na mapach",
  
  ],
};

export const dziczSpotkaniaWPodziemiach = {
  type: "picker",
  list: [
    "Archeolog poszukuje wejścia do ruin",
"Czarownik przeprowadza rytuał",
"Górnik poszukuje żyły cennego kruszcu",
"Grupa spiskowców prowadzi naradę",
"Kamienny kolos sunie przez podziemia",
"Poszukiwacz skarbów próbuje odcyfrować starożytne glify",
"Potwór wyłania się z ciemności",
"Pradawna machina przebija się przez ścianę",
"Sklepienie zaczyna się walić",
"Upiór wspomina światło dnia",
  ],
};

export const dziczSpotkaniaWPrzestworzach = {
  type: "picker",
  list: ["Czarodziej z krzykiem leci w dół",
  "Czarodziej z krzykiem leci w górę",
  "Deszcz zaczyna padać do góry",
  "Nadlatuje samotny potwór-kolos",
  "Nadlatuje stado pomniejszych potworów",
  "Potężny podmuch wiatru porywa wszystko, co nie zostało przymocowane",
  "Z nieba spada grad lodowych odłamków",
  "Z nieba spada gwiazda",
  "Z obłoków wyłania się rozgniewany dżinn",
  "Zawirowanie powietrza ciska drużyną na losowe przyległe pole",
  
  ],
};

export const dziczOdkryciaNaRzece = {
  type: "picker",
  list: [
    "Leże rzecznego potwora",
    "Ławica magicznych ryb",
    "Wejście do podwodnej jaskini",
    "Wielka muszla",
    "Wodorosty cenione przez smakoszy",
    "Wrak barki",
    "Zaciszna zatoczka",
    "Zatopiony kufer",
    "Złoty samorodek wśród kamieni",
    "Zwłoki niesione przez prąd",
  ],
};


export const dziczOdkryciaWPodziemiach = {
  type: "picker",
  list: [
    "Bezdenna czeluść",
    "Gigantyczna pajęczyna",
    "Grobowiec herszta barbarzyńców",
    "Niedokończony krąg rytualny",
    "Niewielkie ruiny",
    "Porzucony sprzęt górniczy",
    "Szkielet przykuty do ściany",
    "Świecące grzyby",
    "Wielkie jajo w skalnym gnieździe",
    "Zamurowany tunel",
  ],
};

export const dziczOdkryciaWPrzestworzach = {
  type: "picker",
  list: [
    "Chmura o smaku i zapachu mleka z miodem",
    "Gniazdo uwite z błyskawic",
    "Lewitujące ciało",
    "Malutka latająca wysepka",
    "Permanentna tęcza",
    "Starożytna machina z trudem unosząca się w powietrzu",
    "Szczerozłoty harpun",
    "Wielkie oko obserwujące, co się dzieje w dole",
    "Wrak latającego okrętu",
    "Zamek wśród chmur",
  ],
};


export const dziczOdkrycia = {
  type: "picker",
  list: [
    "Gorące źródła",
    "Grota za wodospadem",
    "Jednokierunkowy portal na przyległe pole",
    "Kromlech",
    "Leże potwora",
    "Napadnięta karawana",
    "Niewielkie ruiny",
    "Obozowisko myśliwych",
    "Obozowisko uchodźców",
    "Obozowisko zwiadowców",
    "Odpoczywająca karawana",
    "Ogryzione kości potwora",
    "Ołtarz lokalnych bożków",
    "Opuszczona kopalnia",
    "Rzadkie zioła",
    "Smolne sadzawki",
    "Ślady potworów",
    "Trup myśliwego",
    "Wieża czarodzieja",
    "Wrak statku",
  ],
};

export const dziczNocneNiepokoje = {
  type: "picker",
  list: [
    "Duch puszczy sunie przez gęstwinę",
    "Łuna pożaru goreje na horyzoncie",
    "Magiczny fenomen rozbłyskuje w ciemności",
    "Maruderzy szukają łupów",
    "Od zbłąkanej iskry zapala się coś w obozie",
    "Pogoda gwałtownie się pogarsza",
    "Pogoda nieoczekiwanie się poprawia",
    "Potwór przemyka po nocnym niebie",
    "Potwór wywęszył ofiarę",
    "Spadająca gwiazda przelatuje po niebie",
    "Stare drzewo przewraca się z trzaskiem",
    "Uchodźcy szukają schronienia",
    "Upiór szuka ukojenia",
    "Wataha potworów opada łagodnego roślinożercę",
    "Wędrowiec chce podzielić się opowieścią",
    "Wiatr niesie echa wojennych okrzyków",
    "Wiatr przynosi wycie wilków z oddali",
    "Wizerunki nieziemskich istot majaczą w płomieniach ogniska",
    "Z nieba spada drobna część garderoby",
    "Złota moneta lśni wśród poszycia",
  ],
};

export const dziczSkrytki = {
  type: "picker",
  list: [
    "Na dnie sadzawki",
    "Pod kamieniem",
    "Pod kępą mchu",
    "Pod korzeniami drzewa",
    "Pod powalonym drzewem",
    "W bezimiennym grobie",
    "W dziupli",
    "W gąszczu paproci",
    "W kupie gruzu",
    "W lisiej norze",
    "W pryzmie liści",
    "W pszczelim ulu",
    "W ptasim gnieździe",
    "W rozpadlinie",
    "W spróchniałym pniu",
    "W stercie gałęzi",
    "W strumieniu",
    "W wielkiej muszli",
    "Wśród konarów",
    "Wśród kości jelenia",
  ],
};

export const dziczPrzechodnie = {
  type: "picker",
  list: [
    "Archeolog",
    "Bartnik",
    "Dezerter",
    "Druid",
    "Drwal",
    "Dziecko",
    "Leśnik",
    "Łowca potworów",
    "Myśliwy",
    "Okultysta",
    "Partyzant",
    "Rybak",
    "Skald",
    "Skrzat",
    "Traper",
    "Widmo",
    "Wiedźma",
    "Zielarz",
    "Zwiadowca",
    "Zwierzolud",
  ],
};

export const dziczPospoliteRosliny = {
  type: "picker",
  list: [
    "Dziurawiec",
    "Głóg",
    "Jagoda",
    "Jeżyna",
    "Krwawnik",
    "Leszczyna",
    "Malina",
    "Melisa",
    "Mięta",
    "Mniszek",
    "Ostropest",
    "Pokrzywa",
    "Porzeczka",
    "Poziomka",
    "Róża",
    "Rumianek",
    "Skrzyp",
    "Szałwia",
    "Ulęgałka",
    "Wiesiołek",
  ],
};

export const dziczPospolitaZwierzyna = {
  type: "picker",
  list: [
    "Bażant",
    "Borsuk",
    "Dzik",
    "Gęś",
    "Jeleń",
    "Jenot",
    "Kaczka",
    "Kozica",
    "Kuna",
    "Lis",
    "Łoś",
    "Muflon",
    "Niedźwiedź",
    "Ryś",
    "Sarna",
    "Świstak",
    "Tchórz",
    "Wilk",
    "Zając",
    "Żubr",
  ],
};

export const dziczPlotki = {
  type: "picker",
  list: [
    "Czarnoksiężnik Venghast rozpętał wieczną burzę nad swoją wieżą.",
    "Czarnoksiężnik Venghast to przyrodni brat Mrokmora.",
    "Mrokmor jest smokiem.",
    "Mrokmor skazał swoją żonę na śmierć.",
    "W Agdrze kradną wszystko, co nie jest przybite do podłogi.",
    "W Agdrze odbędzie się festyn, który zaszczyci słynna trupa cyrkowa.",
    "W dziczy widuje się ostatnio niepokojąco dużo potworów z głębi lasu.",
    "W dziczy widuje się ostatnio niepokojąco dużo potworów z gór.",
    "W Erteir mają wspaniały zbiór starożytnych artefaktów.",
    "W Erteir mędrcy piją za darmo.",
    "W Lusz mają jajo feniksa dające drugą młodość.",
    "W Lusz wyznaje się więcej bogów, niż jest obywateli.",
    "W Ruinach Miasta Gwiazd potwory stają się coraz straszniejsze.",
    "W Ruinach Miasta Gwiazd spoczywa prawdziwa spadająca gwiazda.",
    "W Ruinach Vol Kraa można zobaczyć cienie przedwiecznych magów.",
    "W Ruinach Vol Kraa znajduje się maszyna zmieniająca ołów w złoto.",
    "W Sirag każdy dostaje dwie żony z przydziału.",
    "W Sirag można dostać w mordę nawet za to, że się dostało w mordę.",
    "Żółta Wiedźma jest piękna i dobra.",
    "Żółta Wiedźma ma stado wiernych gargulców.",
  ],
};

export const miastaSpotkania = {
  type: "picker",
  list: [
    "Bezdomne zwierzęta szukają jedzenia",
    "Gargulce próbują porwać kogoś do pobliskiej wieży",
    "Golem prze na oślep przez miasto",
    "Handlarz wciska tandetę",
    "Jeźdźcy bestii szukają zaczepki",
    "Kapłan namawia do nawrócenia",
    "Kieszonkowiec kradnie sakiewkę",
    "Łowcy niewolników szukają samotnych przyjezdnych",
    "Monstrualny wąż próbuje wciągnąć kogoś do kanału",
    "Niewolnicy dźwigają lektykę",
    "Pijani goście wracają z wesela",
    "Procesja obnosi relikwię wokół świątyni",
    "Straż miejska szuka kozła ofiarnego",
    "Szuler szuka naiwniaków",
    "Tłum obserwuje publiczną egzekucję",
    "Tłum obserwuje występy wędrownych kuglarzy",
    "Tłum protestujących zbiera cięgi od straży miejskiej",
    "Tłum próbuje ukamienować kogoś za herezję",
    "Tłum słucha kazania nawiedzonego kapłana",
    "Żebrak prosi o datek",
  ],
};

export const miastaOdkrycia = {
  type: "picker",
  list: [
    "Dogodny punkt obserwacyjny",
    "Kryjówka bandytów",
    "Kryjówka sekty",
    "Kryjówka szpiegów",
    "Nieczynny warsztat",
    "Nielegalna arena zapaśników",
    "Opuszczony magazyn",
    "Portal na przyległe pole",
    "Sekretne laboratorium alchemika",
    "Sekretne leże przebiegłego potwora",
    "Sekretny dom uciech",
    "Szybkie wejście na dachy",
    "Szybkie zejście do kanałów",
    "Tajna jaskinia hazardu",
    "Tajne przejście do innej części miasta",
    "Ukryty sklepik z kontrabandą",
    "Zakamuflowana wieża czarodzieja",
    "Zakamuflowany targ niewolników",
    "Zamaskowane przejście poza mury miasta",
    "Zamurowana kaplica zapomnianego bożka",
  ],
};

export const miastaNocneNiepokoje = {
  type: "picker",
  list: [
    "Dwaj przechodnie zaczynają się bić",
    "Fragment ulicy zapada się do kanałów poniżej",
    "Grajek uliczny okrutnie fałszuje",
    "Kibice wiwatują na cześć zwycięskiego gladiatora",
    "Ktoś dobija się do zamkniętych drzwi",
    "Ktoś spada z dachu",
    "Na sąsiednim dachu lądują gargulce",
    "Nieludzkie wycie niesie się z oddali",
    "Oddział żołnierzy gdzieś maszeruje",
    "Pieje kur",
    "Pijak śpiewa na całe gardło",
    "Płonie niedaleki gmach",
    "Pogoda gwałtownie się pogarsza",
    "Psy wściekle ujadają",
    "Straż miejska ściga zbiega",
    "Ulicą sunie nocna procesja",
    "Widmo opłakuje swoją stratę",
    "Włamanie do sąsiadów",
    "Z ciemnej uliczki słychać krzyki",
    "Z ciemności wyłania się potwór",
  ],
};

export const miastaSkrytki = {
  type: "picker",
  list: [
    "Na wozie z sianem",
    "Pod daszkiem studni",
    "Pod parapetem",
    "Pod progiem",
    "Pod schodami",
    "W beczce na deszczówkę",
    "W ciemnym zaułku",
    "W doniczce z kwiatkiem",
    "W pękniętej amforze",
    "W porzuconej klatce",
    "W porzuconej torbie",
    "W psiej budzie",
    "W pustostanie",
    "W rynnie",
    "W skrzynce na listy",
    "W starej skrzynce",
    "W stercie odpadków",
    "W szczurzej norze",
    "W zapomnianym koszyku",
    "Za obluzowaną cegłą",
  ],
};

export const miastaPrzechodnie = {
  type: "picker",
  list: [
    "Adept sztuk tajemnych",
    "Cieśla",
    "Dziecko",
    "Flisak",
    "Gospodyni",
    "Handlarz",
    "Kucharz",
    "Kurtyzana",
    "Murarz",
    "Pasterz",
    "Piwowar",
    "Posłaniec",
    "Robotnik",
    "Rolnik",
    "Rybak",
    "Skryba",
    "Sługa",
    "Strażnik miejski",
    "Szlachcic",
    "Żebrak",
  ],
};

export const miastaPrzechodniePrzydomki = {
  type: "picker",
  list: [
    "Blondi",
    "Bury",
    "Buźka",
    "Dziku",
    "Grom",
    "Gruby",
    "Japa",
    "Łysy",
    "Maruda",
    "Oczko",
    "Palec",
    "Pędzel",
    "Pięść",
    "Pyza",
    "Rogal",
    "Rudy",
    "Ryba",
    "Smoku",
    "Wężu",
    "Wilczarz",
  ],
};

export const miastaPrzechodnieZnaki = {
  type: "picker",
  list: [
    "Blizna na plecach",
    "Blizna na torsie",
    "Blizna na twarzy",
    "Blizny na nogach",
    "Blizny na rękach",
    "Brakujące oko",
    "Brakujące ucho",
    "Brakujący palec",
    "Brakujący ząb",
    "Łysina",
    "Nietypowy kolor oczu",
    "Nietypowy kolor skóry",
    "Nietypowy kolor włosów",
    "Rozdwojony język",
    "Tatuaż: cytat",
    "Tatuaż: obsceniczny",
    "Tatuaż: roślina",
    "Tatuaż: symbol",
    "Tatuaż: zwierzę",
    "Złamany nos",
  ],
};

export const miastaPlotki = {
  type: "picker",
  list: [
    "[Imię] jest wiedźmą.",
    "[Imię] skupuje artefakty, ale słabo płaci.",
    "[Imię] szuka eskorty na wyprawę do (nazwa miasta).",
    "[Imię] szuka kogoś od brudnej roboty.",
    "[Imię] urodziła potwora.",
    "[Imię] współpracuje z barbarzyńcami zza gór.",
    "Coś się zagnieździło w kanałach.",
    "Część zabudowy w mieście to gigantyczne, uśpione golemy.",
    "Miejscowi bardowie podzielili między siebie miasto i wpływy.",
    "Na dachu [nazwa lokalu] gniazdują skrzydlate potwory.",
    "Nocą po ulicach krążą łowcy niewolników.",
    "Nowe monety są z kiepskiego kruszcu.",
    "Posągi przed pałacem to spetryfikowani ludzie.",
    "Straż miejska poszukuje [imię].",
    "Szykuje się zbrojny przewrót w mieście.",
    "W [nazwa lokalu] chrzczą piwo na potęgę.",
    "W [nazwa lokalu] podają szczurze mięso.",
    "W beczkach i skrzynkach można czasem znaleźć złoto.",
    "W świątyni [imię bożka] zdejmują klątwy za darmo.",
    "Walki gladiatorów z potworami są pozorowane.",
  ],
};

export const ruinySpotkania = {
  type: "picker",
  list: [
    "Archeolog poszukuje wiedzy",
    "Archeolog ucieka z walącego się chodnika",
    "Banita szuka kryjówki",
    "Budowniczowie szukają budulca",
    "Dziecko zbiera kwiaty",
    "Eremita kreśli na ścianach tajemnicze symbole",
    "Grupa małolatów majstruje przy dziwacznej machinie",
    "Łowcy nagród szukają zbiega",
    "Najeźdźcy budują obóz",
    "Okultysta budzi śpiące monstrum",
    "Okultyści przeprowadzają rytuał",
    "Potwór szuka drogi na wolność",
    "Potwór szuka ofiar",
    "Potwór szuka pana",
    "Potwór szuka poddanych",
    "Pustelnik szuka samotności",
    "Rabuś poszukuje łupów",
    "Rabuś utknął w morderczej pułapce",
    "Uchodźcy poszukują schronienia",
    "Zjawa opowiada o dawnych czasach",
  ],
};

export const ruinyOdkrycia = {
  type: "picker",
  list: [
    "Imponująca rozdrabniarka",
    "Komin wyrzucający kłęby pary",
    "Komora hibernacyjna",
    "Kości starożytnych mieszkańców ruin",
    "Krąg rytualny",
    "Kryjówka banitów",
    "Księga w nieznanym języku",
    "Masywna zgniatarka",
    "Maszyna produkująca świecące szklane sfery",
    "Maszyneria podgrzewająca wodę",
    "Maszyneria przyciągająca pioruny",
    "Niedokończony golem",
    "Obozowisko archeologów",
    "Portal do losowej izby",
    "Potwór w wielkim szklanym zbiorniku z cieczą",
    "Projekt niewyobrażalnie skomplikowanego urządzenia",
    "Pudło fikuśnych narzędzi",
    "Skrzynka skomplikowanych części maszyn",
    "Stacja pomp napędzająca lokalny strumień",
    "Wielkie kadzie wypełnione stężałą masą",
  ],
};

export const ruinyNocneNiepokoje = {
  type: "picker",
  list: [
    "Antyczna maszyneria zaczyna hałasować",
    "Całe ruiny spowija mgła",
    "Drzwi zatrzaskują się z hukiem",
    "Duchy snują się po tunelach",
    "Dwa pomieszczenia zamieniają się miejscami",
    "Ktoś woła o pomoc z odległego zaułka",
    "Na ścianach zaczynają połyskiwać mistyczne glify",
    "Na ścianie rozkwita kolorowa pleśń",
    "Okultyści zaczynają przygotowywać rytuał",
    "Otwiera się ukryte przejście",
    "Stado nietoperzy przelatuje pod sufitem",
    "Starożytny golem sunie przez lochy",
    "W całych ruinach słychać tykanie",
    "W komnacie zapala się magiczne światło",
    "W sąsiedniej komnacie coś wybucha",
    "Z ciemności wypełza potwór",
    "Z sufitu zaczyna kapać woda",
    "Zabłąkany rabuś szuka wyjścia",
    "Zapada się część podłogi",
    "Zawala się pobliski korytarz",
  ],
};

export const ruinySkrytki = {
  type: "picker",
  list: [
    "Pod gzymsem",
    "Pod ławą",
    "Pod podłogą",
    "W amforze",
    "W baryłce",
    "W donicy",
    "W koksowniku",
    "W odpływie",
    "W posągu",
    "W sarkofagu",
    "W skrzyni",
    "W stercie gruzu",
    "W stercie kości",
    "W stercie złomu",
    "W studni",
    "W torbie",
    "W wentylacji",
    "Za fałszywą ścianą",
    "Za obluzowaną cegłą",
    "Za ołtarzem",
  ],
};

export const ruinyPulapki = {
  type: "picker",
  list: [
    "Armatki wodne",
    "Głośny alarm",
    "Kamienna kula",
    "Kolce w podłodze",
    "Komnatę wypełnia gaz",
    "Komnatę wypełnia piasek",
    "Komnatę wypełnia woda",
    "Komnatę wypełniają płomienie",
    "Miażdżące ściany",
    "Miażdżący sufit",
    "Miny",
    "Miotacze kwasu",
    "Miotacze ognia",
    "Miotacze pary",
    "Miotacze piorunów",
    "Piły tarczowe w ścianach",
    "Promienie śmierci",
    "Wahadło śmierci",
    "Wyrzutnie zatrutych strzałek",
    "Zapadnia z kolcami",
  ],
};

export const ruinySny = {
  type: "picker",
  list: [
    "Dziwna istota pospiesznie pakująca księgi i zwoje",
    "Dziwna istota rzeźbiąca fantastycznego kolosa",
    "Dziwna istota strzelająca z tajemniczej broni",
    "Dziwna istota wznosząca toast na tle płomieni",
    "Dziwna istota z krzykiem uciekająca przed czarną powodzią",
    "Dziwne istoty kreślące skomplikowane symbole",
    "Dziwne istoty malujące stworzenia jeszcze dziwniejsze",
    "Dziwne istoty obserwujące miasto z wysokiej wieży",
    "Dziwne istoty przyzywające szkaradne monstrum",
    "Dziwne istoty wpatrzone w zachwycający klejnot na piedestale",
    "Dziwne istoty zamykające masywne drzwi skarbca",
    "Gigantyczna maszyneria pracująca pełną parą",
    "Liczna armia dziwnych istot maszerująca na zachód",
    "Niezdobyta twierdza rozpadająca się jak domek z kart",
    "Para dziwnych istot wpatrzonych w gwiazdy",
    "Para dziwnych istot z uśmiechem idąca w płomienie",
    "Rodzina dziwnych istot wewnątrz mechanicznego pojazdu",
    "Tłumy dziwnych istot na gwarnym bazarze",
    "Tłumy wiernych składających pokłony majestatycznemu posągowi",
    "Wieża szybująca ku gwiazdom",
  ],
};

// Wieże: komnaty
export const wiezeKomnaty = {
  type: "picker",
  list: [
    "Alkowa",
    "Biblioteka",
    "Gabinet osobliwości",
    "Garderoba",
    "Komnata medytacyjna",
    "Krypta",
    "Kuchnia",
    "Kuźnia",
    "Loch",
    "Łazienka",
    "Magazyn komponentów",
    "Obserwatorium astrologiczne",
    "Pokoje sług",
    "Pokój gościnny",
    "Pracownia alchemiczna",
    "Pracownia jubilerska",
    "Sala operacyjna",
    "Sala przywołań",
    "Warsztat",
    "Zbrojownia"
  ]
};

// Wieże: anomalie
export const wiezeAnomalie = {
  type: "picker",
  list: [
    "Dywany zmieniające wzory",
    "Gapiące się obrazy",
    "Kot chodzący po suficie",
    "Krwawiące ściany",
    "Lewitujące przedmioty",
    "Nieskończone klepsydry",
    "Nieumarłe karaluchy",
    "Okna pokazujące inne światy",
    "Permanentne pajęczyny",
    "Płomienie rzucające ciecie",
    "Rośliny łaszące się jak koty",
    "Samogrające instrumenty",
    "Samopiszące się księgi",
    "Tajemnicze szepty",
    "Tańczące światła",
    "Wędrujące meble",
    "Wieczne przeciągi",
    "Zapach morskiej bryzy",
    "Zatrzaskujące się drzwi",
    "Zegary chodzące wspak"
  ]
};

// Wieże: skrytki
export const wiezeSkrytki = {
  type: "picker",
  list: [
    "Między książkami",
    "Pod dywanem",
    "Pod kafelkiem",
    "Pod parapetem",
    "W beczce",
    "W czaszce",
    "W kominku",
    "W odpływie",
    "W posągu",
    "W rękawie szaty",
    "W sakwie",
    "W skrzyni",
    "W słoju szlamu",
    "W starej zbroi",
    "W żyrandolu",
    "Wewnątrz nogi mebla",
    "Wśród butelek",
    "Za obluzowaną cegłą",
    "Za obrazem",
    "Za pajęczyną"
  ]
};

// Wieże: słudzy
export const wiezeSludzy = {
  type: "picker",
  list: [
    "Adepci magii",
    "Bezduszni jaszczuroludzie",
    "Czarujące pokojówki",
    "Dwunożne kozły",
    "Dystyngowani lokaje",
    "Frywolne duszki",
    "Gnijące zombie",
    "Inteligentne szczury",
    "Lamentujące upiory",
    "Niedopłacani najemnicy",
    "Ociężałe golemy",
    "Posłuszne klony",
    "Prostoduszne ogry",
    "Przebiegli zabójcy",
    "Szantażowani jeńcy",
    "Szkaradne karły",
    "Wielkie pająki",
    "Zaklęte zbroje",
    "Złośliwe impy",
    "Znudzone kariatydy"
  ]
};

// Wieże: księgi
export const wiezeKsiegi = {
  type: "picker",
  list: [
    "Almanach Alchemika",
    "Bestiariusz Przywoływacza",
    "Demonologia dla Zuchwałych",
    "Dzielny Mały Kucyk",
    "Historia Zapomnianych Ziem",
    "Pomniejsze Kulty",
    "Portale Zapomnianych Ziem",
    "Przedwieczne Monstra",
    "Przewodnik po Agdrze",
    "Przewodnik po Erteir",
    "Przewodnik po Lusz",
    "Przewodnik po Sirag",
    "Sekrety Świata Astralnego",
    "Skarby Zapomnianych Ziem",
    "Smoki przez Wieki",
    "Tajemnice Astrologii",
    "Tajniki Nekromancji",
    "W Ogniu Pożądania",
    "Wodzowie i Zdobywcy",
    "Zmień Swoje Życie"
  ]
};

// Wieże: komponenty
export const wiezeKomponenty = {
  type: "picker",
  list: [
    "Atrament krakena",
    "Czaszka licza",
    "Jedwab ogromnego pająka",
    "Kły hydry",
    "Krew amfisbeny",
    "Kwiat drzewca",
    "Łajno katoblepasa",
    "Łapa gargulca",
    "Oko bazyliszka",
    "Pazur gryfa",
    "Pióro feniksa",
    "Róg demona",
    "Róg jednorożca",
    "Serce trolla",
    "Smocze łuski",
    "Ścięgna ogra",
    "Śluz grzyboluda",
    "Włos nimfy",
    "Włos olbrzyma",
    "Żądło mantykory"
  ]
};

// Wieże: gwiazdozbiory
export const wiezeGwiazdozbiory = {
  type: "picker",
  list: [
    "Czarnoksiężnik",
    "Giermek",
    "Heros",
    "Klejnot",
    "Król",
    "Księżniczka",
    "Miecz",
    "Okręt",
    "Rumak",
    "Smok",
    "Wieża",
    "Żółw"
  ]
};

// Wieże: znaki
export const wiezeZnaki = {
  type: "picker",
  list: [
    "Kometa",
    "Koniunkcja",
    "Narodziny gwiazdy",
    "Nowa planeta",
    "Nowy gwiazdozbiór",
    "Nowy księżyc",
    "Rozbłysk słoneczny",
    "Spadająca gwiazda",
    "Zaćmienie",
    "Zderzenie gwiazd",
    "Zgaśnięcie gwiazdy",
    "Zorza"
  ]
};


// export const dziczSpotkania = {
//   type: "picker",
//   list: [
//   ],
// };
