export const dziczSpotkania = {
  type: "picker",
  list: [
    "Błędne ogniki prowadzą na śmierć",
"Drużyna zabłądziła na losowe pole przyległe do docelowego",
"Frywolne duszki szukają rozrywki",
"Goniec wiezie ważne wieści",
"Maruderzy szukają łatwych ofiar",
"Myśliwy tropi groźnego potwora",
"Negocjujące sekty – obie szukają wiernych",
"Niespokojne duchy szukają ukojenia",
"Okultyści odprawiają rytuał",
"Partyzanci przygotowują zasadzkę",
"Plądrowana osada – zarówno zbójcy, jak i ofiary przyjmą wsparcie",
"Potwór atakuje każdego w zasięgu wzroku",
"Potwór z młodymi broni potomstwa",
"Pustelnik szuka odosobnienia",
"Sprzeczający się przyjaciele – obaj szukają poparcia",
"Uchodźcy szukają pomocy w przeprawie",
"Walczące oddziały – oba szukają wsparcia",
"Zielarz szuka rzadkich ziół",
"Zwiadowcy starają się przemknąć niepostrzeżenie",
"Żołnierz szuka pomocy medycznej", 
  ],
};

export const dziczSpotkaniaNaRzece = {
  type: "picker",
  list: ["Bobry budują tamę",
  "Drwale spławiają drewno",
  "Flisacy naprawiają tratwę",
  "Kapłani dokonują rytualnych ablucji",
  "Mielizna nieoznaczona na mapach",
  "Potwór wynurza się z głębin",
  "Robotnicy budują most",
  "Wędkarz przysnął na brzegu",
  "Wędrowiec tonie",
  "Wodospad nieoznaczony na mapach",
  
  ],
};

export const dziczSpotkaniaWPodziemiach = {
  type: "picker",
  list: [
    "Archeolog poszukuje wejścia do ruin",
"Czarownik przeprowadza rytuał",
"Górnik poszukuje żyły cennego kruszcu",
"Grupa spiskowców prowadzi naradę",
"Kamienny kolos sunie przez podziemia",
"Poszukiwacz skarbów próbuje odcyfrować starożytne glify",
"Potwór wyłania się z ciemności",
"Pradawna machina przebija się przez ścianę",
"Sklepienie zaczyna się walić",
"Upiór wspomina światło dnia",
  ],
};

export const dziczSpotkaniaWPrzestworzach = {
  type: "picker",
  list: ["Czarodziej z krzykiem leci w dół",
  "Czarodziej z krzykiem leci w górę",
  "Deszcz zaczyna padać do góry",
  "Nadlatuje samotny potwór-kolos",
  "Nadlatuje stado pomniejszych potworów",
  "Potężny podmuch wiatru porywa wszystko, co nie zostało przymocowane",
  "Z nieba spada grad lodowych odłamków",
  "Z nieba spada gwiazda",
  "Z obłoków wyłania się rozgniewany dżinn",
  "Zawirowanie powietrza ciska drużyną na losowe przyległe pole",
  
  ],
};

export const dziczOdkryciaNaRzece = {
  type: "picker",
  list: [
    "Leże rzecznego potwora",
    "Ławica magicznych ryb",
    "Wejście do podwodnej jaskini",
    "Wielka muszla",
    "Wodorosty cenione przez smakoszy",
    "Wrak barki",
    "Zaciszna zatoczka",
    "Zatopiony kufer",
    "Złoty samorodek wśród kamieni",
    "Zwłoki niesione przez prąd",
  ],
};


export const dziczOdkryciaWPodziemiach = {
  type: "picker",
  list: [
    "Bezdenna czeluść",
    "Gigantyczna pajęczyna",
    "Grobowiec herszta barbarzyńców",
    "Niedokończony krąg rytualny",
    "Niewielkie ruiny",
    "Porzucony sprzęt górniczy",
    "Szkielet przykuty do ściany",
    "Świecące grzyby",
    "Wielkie jajo w skalnym gnieździe",
    "Zamurowany tunel",
  ],
};

export const dziczOdkryciaWPrzestworzach = {
  type: "picker",
  list: [
    "Chmura o smaku i zapachu mleka z miodem",
    "Gniazdo uwite z błyskawic",
    "Lewitujące ciało",
    "Malutka latająca wysepka",
    "Permanentna tęcza",
    "Starożytna machina z trudem unosząca się w powietrzu",
    "Szczerozłoty harpun",
    "Wielkie oko obserwujące, co się dzieje w dole",
    "Wrak latającego okrętu",
    "Zamek wśród chmur",
  ],
};


export const dziczOdkrycia = {
  type: "picker",
  list: [
    "Gorące źródła",
    "Grota za wodospadem",
    "Jednokierunkowy portal na przyległe pole",
    "Kromlech",
    "Leże potwora",
    "Napadnięta karawana",
    "Niewielkie ruiny",
    "Obozowisko myśliwych",
    "Obozowisko uchodźców",
    "Obozowisko zwiadowców",
    "Odpoczywająca karawana",
    "Ogryzione kości potwora",
    "Ołtarz lokalnych bożków",
    "Opuszczona kopalnia",
    "Rzadkie zioła",
    "Smolne sadzawki",
    "Ślady potworów",
    "Trup myśliwego",
    "Wieża czarodzieja",
    "Wrak statku",
  ],
};

export const dziczNocneNiepokoje = {
  type: "picker",
  list: [
    "Duch puszczy sunie przez gęstwinę",
    "Łuna pożaru goreje na horyzoncie",
    "Magiczny fenomen rozbłyskuje w ciemności",
    "Maruderzy szukają łupów",
    "Od zbłąkanej iskry zapala się coś w obozie",
    "Pogoda gwałtownie się pogarsza",
    "Pogoda nieoczekiwanie się poprawia",
    "Potwór przemyka po nocnym niebie",
    "Potwór wywęszył ofiarę",
    "Spadająca gwiazda przelatuje po niebie",
    "Stare drzewo przewraca się z trzaskiem",
    "Uchodźcy szukają schronienia",
    "Upiór szuka ukojenia",
    "Wataha potworów opada łagodnego roślinożercę",
    "Wędrowiec chce podzielić się opowieścią",
    "Wiatr niesie echa wojennych okrzyków",
    "Wiatr przynosi wycie wilków z oddali",
    "Wizerunki nieziemskich istot majaczą w płomieniach ogniska",
    "Z nieba spada drobna część garderoby",
    "Złota moneta lśni wśród poszycia",
  ],
};

export const dziczSkrytki = {
  type: "picker",
  list: [
    "Na dnie sadzawki",
    "Pod kamieniem",
    "Pod kępą mchu",
    "Pod korzeniami drzewa",
    "Pod powalonym drzewem",
    "W bezimiennym grobie",
    "W dziupli",
    "W gąszczu paproci",
    "W kupie gruzu",
    "W lisiej norze",
    "W pryzmie liści",
    "W pszczelim ulu",
    "W ptasim gnieździe",
    "W rozpadlinie",
    "W spróchniałym pniu",
    "W stercie gałęzi",
    "W strumieniu",
    "W wielkiej muszli",
    "Wśród konarów",
    "Wśród kości jelenia",
  ],
};

export const dziczPrzechodnie = {
  type: "picker",
  list: [
    "Archeolog",
    "Bartnik",
    "Dezerter",
    "Druid",
    "Drwal",
    "Dziecko",
    "Leśnik",
    "Łowca potworów",
    "Myśliwy",
    "Okultysta",
    "Partyzant",
    "Rybak",
    "Skald",
    "Skrzat",
    "Traper",
    "Widmo",
    "Wiedźma",
    "Zielarz",
    "Zwiadowca",
    "Zwierzolud",
  ],
};

export const dziczPospoliteRosliny = {
  type: "picker",
  list: [
    "Dziurawiec",
    "Głóg",
    "Jagoda",
    "Jeżyna",
    "Krwawnik",
    "Leszczyna",
    "Malina",
    "Melisa",
    "Mięta",
    "Mniszek",
    "Ostropest",
    "Pokrzywa",
    "Porzeczka",
    "Poziomka",
    "Róża",
    "Rumianek",
    "Skrzyp",
    "Szałwia",
    "Ulęgałka",
    "Wiesiołek",
  ],
};

export const dziczPospolitaZwierzyna = {
  type: "picker",
  list: [
    "Bażant",
    "Borsuk",
    "Dzik",
    "Gęś",
    "Jeleń",
    "Jenot",
    "Kaczka",
    "Kozica",
    "Kuna",
    "Lis",
    "Łoś",
    "Muflon",
    "Niedźwiedź",
    "Ryś",
    "Sarna",
    "Świstak",
    "Tchórz",
    "Wilk",
    "Zając",
    "Żubr",
  ],
};

export const dziczPlotki = {
  type: "picker",
  list: [
    "Czarnoksiężnik Venghast rozpętał wieczną burzę nad swoją wieżą.",
    "Czarnoksiężnik Venghast to przyrodni brat Mrokmora.",
    "Mrokmor jest smokiem.",
    "Mrokmor skazał swoją żonę na śmierć.",
    "W Agdrze kradną wszystko, co nie jest przybite do podłogi.",
    "W Agdrze odbędzie się festyn, który zaszczyci słynna trupa cyrkowa.",
    "W dziczy widuje się ostatnio niepokojąco dużo potworów z głębi lasu.",
    "W dziczy widuje się ostatnio niepokojąco dużo potworów z gór.",
    "W Erteir mają wspaniały zbiór starożytnych artefaktów.",
    "W Erteir mędrcy piją za darmo.",
    "W Lusz mają jajo feniksa dające drugą młodość.",
    "W Lusz wyznaje się więcej bogów, niż jest obywateli.",
    "W Ruinach Miasta Gwiazd potwory stają się coraz straszniejsze.",
    "W Ruinach Miasta Gwiazd spoczywa prawdziwa spadająca gwiazda.",
    "W Ruinach Vol Kraa można zobaczyć cienie przedwiecznych magów.",
    "W Ruinach Vol Kraa znajduje się maszyna zmieniająca ołów w złoto.",
    "W Sirag każdy dostaje dwie żony z przydziału.",
    "W Sirag można dostać w mordę nawet za to, że się dostało w mordę.",
    "Żółta Wiedźma jest piękna i dobra.",
    "Żółta Wiedźma ma stado wiernych gargulców.",
  ],
};

export const miastaSpotkania = {
  type: "picker",
  list: [
    "Bezdomne zwierzęta szukają jedzenia",
    "Gargulce próbują porwać kogoś do pobliskiej wieży",
    "Golem prze na oślep przez miasto",
    "Handlarz wciska tandetę",
    "Jeźdźcy bestii szukają zaczepki",
    "Kapłan namawia do nawrócenia",
    "Kieszonkowiec kradnie sakiewkę",
    "Łowcy niewolników szukają samotnych przyjezdnych",
    "Monstrualny wąż próbuje wciągnąć kogoś do kanału",
    "Niewolnicy dźwigają lektykę",
    "Pijani goście wracają z wesela",
    "Procesja obnosi relikwię wokół świątyni",
    "Straż miejska szuka kozła ofiarnego",
    "Szuler szuka naiwniaków",
    "Tłum obserwuje publiczną egzekucję",
    "Tłum obserwuje występy wędrownych kuglarzy",
    "Tłum protestujących zbiera cięgi od straży miejskiej",
    "Tłum próbuje ukamienować kogoś za herezję",
    "Tłum słucha kazania nawiedzonego kapłana",
    "Żebrak prosi o datek",
  ],
};

export const miastaOdkrycia = {
  type: "picker",
  list: [
    "Dogodny punkt obserwacyjny",
    "Kryjówka bandytów",
    "Kryjówka sekty",
    "Kryjówka szpiegów",
    "Nieczynny warsztat",
    "Nielegalna arena zapaśników",
    "Opuszczony magazyn",
    "Portal na przyległe pole",
    "Sekretne laboratorium alchemika",
    "Sekretne leże przebiegłego potwora",
    "Sekretny dom uciech",
    "Szybkie wejście na dachy",
    "Szybkie zejście do kanałów",
    "Tajna jaskinia hazardu",
    "Tajne przejście do innej części miasta",
    "Ukryty sklepik z kontrabandą",
    "Zakamuflowana wieża czarodzieja",
    "Zakamuflowany targ niewolników",
    "Zamaskowane przejście poza mury miasta",
    "Zamurowana kaplica zapomnianego bożka",
  ],
};

export const miastaNocneNiepokoje = {
  type: "picker",
  list: [
    "Dwaj przechodnie zaczynają się bić",
    "Fragment ulicy zapada się do kanałów poniżej",
    "Grajek uliczny okrutnie fałszuje",
    "Kibice wiwatują na cześć zwycięskiego gladiatora",
    "Ktoś dobija się do zamkniętych drzwi",
    "Ktoś spada z dachu",
    "Na sąsiednim dachu lądują gargulce",
    "Nieludzkie wycie niesie się z oddali",
    "Oddział żołnierzy gdzieś maszeruje",
    "Pieje kur",
    "Pijak śpiewa na całe gardło",
    "Płonie niedaleki gmach",
    "Pogoda gwałtownie się pogarsza",
    "Psy wściekle ujadają",
    "Straż miejska ściga zbiega",
    "Ulicą sunie nocna procesja",
    "Widmo opłakuje swoją stratę",
    "Włamanie do sąsiadów",
    "Z ciemnej uliczki słychać krzyki",
    "Z ciemności wyłania się potwór",
  ],
};

export const miastaSkrytki = {
  type: "picker",
  list: [
    "Na wozie z sianem",
    "Pod daszkiem studni",
    "Pod parapetem",
    "Pod progiem",
    "Pod schodami",
    "W beczce na deszczówkę",
    "W ciemnym zaułku",
    "W doniczce z kwiatkiem",
    "W pękniętej amforze",
    "W porzuconej klatce",
    "W porzuconej torbie",
    "W psiej budzie",
    "W pustostanie",
    "W rynnie",
    "W skrzynce na listy",
    "W starej skrzynce",
    "W stercie odpadków",
    "W szczurzej norze",
    "W zapomnianym koszyku",
    "Za obluzowaną cegłą",
  ],
};

export const miastaPrzechodnie = {
  type: "picker",
  list: [
    "Adept sztuk tajemnych",
    "Cieśla",
    "Dziecko",
    "Flisak",
    "Gospodyni",
    "Handlarz",
    "Kucharz",
    "Kurtyzana",
    "Murarz",
    "Pasterz",
    "Piwowar",
    "Posłaniec",
    "Robotnik",
    "Rolnik",
    "Rybak",
    "Skryba",
    "Sługa",
    "Strażnik miejski",
    "Szlachcic",
    "Żebrak",
  ],
};

export const miastaPrzechodniePrzydomki = {
  type: "picker",
  list: [
    "Blondi",
    "Bury",
    "Buźka",
    "Dziku",
    "Grom",
    "Gruby",
    "Japa",
    "Łysy",
    "Maruda",
    "Oczko",
    "Palec",
    "Pędzel",
    "Pięść",
    "Pyza",
    "Rogal",
    "Rudy",
    "Ryba",
    "Smoku",
    "Wężu",
    "Wilczarz",
  ],
};

export const miastaPrzechodnieZnaki = {
  type: "picker",
  list: [
    "Blizna na plecach",
    "Blizna na torsie",
    "Blizna na twarzy",
    "Blizny na nogach",
    "Blizny na rękach",
    "Brakujące oko",
    "Brakujące ucho",
    "Brakujący palec",
    "Brakujący ząb",
    "Łysina",
    "Nietypowy kolor oczu",
    "Nietypowy kolor skóry",
    "Nietypowy kolor włosów",
    "Rozdwojony język",
    "Tatuaż: cytat",
    "Tatuaż: obsceniczny",
    "Tatuaż: roślina",
    "Tatuaż: symbol",
    "Tatuaż: zwierzę",
    "Złamany nos",
  ],
};

export const miastaPlotki = {
  type: "picker",
  list: [
    "[Imię] jest wiedźmą.",
    "[Imię] skupuje artefakty, ale słabo płaci.",
    "[Imię] szuka eskorty na wyprawę do (nazwa miasta).",
    "[Imię] szuka kogoś od brudnej roboty.",
    "[Imię] urodziła potwora.",
    "[Imię] współpracuje z barbarzyńcami zza gór.",
    "Coś się zagnieździło w kanałach.",
    "Część zabudowy w mieście to gigantyczne, uśpione golemy.",
    "Miejscowi bardowie podzielili między siebie miasto i wpływy.",
    "Na dachu [nazwa lokalu] gniazdują skrzydlate potwory.",
    "Nocą po ulicach krążą łowcy niewolników.",
    "Nowe monety są z kiepskiego kruszcu.",
    "Posągi przed pałacem to spetryfikowani ludzie.",
    "Straż miejska poszukuje [imię].",
    "Szykuje się zbrojny przewrót w mieście.",
    "W [nazwa lokalu] chrzczą piwo na potęgę.",
    "W [nazwa lokalu] podają szczurze mięso.",
    "W beczkach i skrzynkach można czasem znaleźć złoto.",
    "W świątyni [imię bożka] zdejmują klątwy za darmo.",
    "Walki gladiatorów z potworami są pozorowane.",
  ],
};

export const ruinySpotkania = {
  type: "picker",
  list: [
    "Archeolog poszukuje wiedzy",
    "Archeolog ucieka z walącego się chodnika",
    "Banita szuka kryjówki",
    "Budowniczowie szukają budulca",
    "Dziecko zbiera kwiaty",
    "Eremita kreśli na ścianach tajemnicze symbole",
    "Grupa małolatów majstruje przy dziwacznej machinie",
    "Łowcy nagród szukają zbiega",
    "Najeźdźcy budują obóz",
    "Okultysta budzi śpiące monstrum",
    "Okultyści przeprowadzają rytuał",
    "Potwór szuka drogi na wolność",
    "Potwór szuka ofiar",
    "Potwór szuka pana",
    "Potwór szuka poddanych",
    "Pustelnik szuka samotności",
    "Rabuś poszukuje łupów",
    "Rabuś utknął w morderczej pułapce",
    "Uchodźcy poszukują schronienia",
    "Zjawa opowiada o dawnych czasach",
  ],
};

export const ruinyOdkrycia = {
  type: "picker",
  list: [
    "Imponująca rozdrabniarka",
    "Komin wyrzucający kłęby pary",
    "Komora hibernacyjna",
    "Kości starożytnych mieszkańców ruin",
    "Krąg rytualny",
    "Kryjówka banitów",
    "Księga w nieznanym języku",
    "Masywna zgniatarka",
    "Maszyna produkująca świecące szklane sfery",
    "Maszyneria podgrzewająca wodę",
    "Maszyneria przyciągająca pioruny",
    "Niedokończony golem",
    "Obozowisko archeologów",
    "Portal do losowej izby",
    "Potwór w wielkim szklanym zbiorniku z cieczą",
    "Projekt niewyobrażalnie skomplikowanego urządzenia",
    "Pudło fikuśnych narzędzi",
    "Skrzynka skomplikowanych części maszyn",
    "Stacja pomp napędzająca lokalny strumień",
    "Wielkie kadzie wypełnione stężałą masą",
  ],
};

export const ruinyNocneNiepokoje = {
  type: "picker",
  list: [
    "Antyczna maszyneria zaczyna hałasować",
    "Całe ruiny spowija mgła",
    "Drzwi zatrzaskują się z hukiem",
    "Duchy snują się po tunelach",
    "Dwa pomieszczenia zamieniają się miejscami",
    "Ktoś woła o pomoc z odległego zaułka",
    "Na ścianach zaczynają połyskiwać mistyczne glify",
    "Na ścianie rozkwita kolorowa pleśń",
    "Okultyści zaczynają przygotowywać rytuał",
    "Otwiera się ukryte przejście",
    "Stado nietoperzy przelatuje pod sufitem",
    "Starożytny golem sunie przez lochy",
    "W całych ruinach słychać tykanie",
    "W komnacie zapala się magiczne światło",
    "W sąsiedniej komnacie coś wybucha",
    "Z ciemności wypełza potwór",
    "Z sufitu zaczyna kapać woda",
    "Zabłąkany rabuś szuka wyjścia",
    "Zapada się część podłogi",
    "Zawala się pobliski korytarz",
  ],
};

export const ruinySkrytki = {
  type: "picker",
  list: [
    "Pod gzymsem",
    "Pod ławą",
    "Pod podłogą",
    "W amforze",
    "W baryłce",
    "W donicy",
    "W koksowniku",
    "W odpływie",
    "W posągu",
    "W sarkofagu",
    "W skrzyni",
    "W stercie gruzu",
    "W stercie kości",
    "W stercie złomu",
    "W studni",
    "W torbie",
    "W wentylacji",
    "Za fałszywą ścianą",
    "Za obluzowaną cegłą",
    "Za ołtarzem",
  ],
};

export const ruinyPulapki = {
  type: "picker",
  list: [
    "Armatki wodne",
    "Głośny alarm",
    "Kamienna kula",
    "Kolce w podłodze",
    "Komnatę wypełnia gaz",
    "Komnatę wypełnia piasek",
    "Komnatę wypełnia woda",
    "Komnatę wypełniają płomienie",
    "Miażdżące ściany",
    "Miażdżący sufit",
    "Miny",
    "Miotacze kwasu",
    "Miotacze ognia",
    "Miotacze pary",
    "Miotacze piorunów",
    "Piły tarczowe w ścianach",
    "Promienie śmierci",
    "Wahadło śmierci",
    "Wyrzutnie zatrutych strzałek",
    "Zapadnia z kolcami",
  ],
};

export const ruinySny = {
  type: "picker",
  list: [
    "Dziwna istota pospiesznie pakująca księgi i zwoje",
    "Dziwna istota rzeźbiąca fantastycznego kolosa",
    "Dziwna istota strzelająca z tajemniczej broni",
    "Dziwna istota wznosząca toast na tle płomieni",
    "Dziwna istota z krzykiem uciekająca przed czarną powodzią",
    "Dziwne istoty kreślące skomplikowane symbole",
    "Dziwne istoty malujące stworzenia jeszcze dziwniejsze",
    "Dziwne istoty obserwujące miasto z wysokiej wieży",
    "Dziwne istoty przyzywające szkaradne monstrum",
    "Dziwne istoty wpatrzone w zachwycający klejnot na piedestale",
    "Dziwne istoty zamykające masywne drzwi skarbca",
    "Gigantyczna maszyneria pracująca pełną parą",
    "Liczna armia dziwnych istot maszerująca na zachód",
    "Niezdobyta twierdza rozpadająca się jak domek z kart",
    "Para dziwnych istot wpatrzonych w gwiazdy",
    "Para dziwnych istot z uśmiechem idąca w płomienie",
    "Rodzina dziwnych istot wewnątrz mechanicznego pojazdu",
    "Tłumy dziwnych istot na gwarnym bazarze",
    "Tłumy wiernych składających pokłony majestatycznemu posągowi",
    "Wieża szybująca ku gwiazdom",
  ],
};

// Wieże: komnaty
export const wiezeKomnaty = {
  type: "picker",
  list: [
    "Alkowa",
    "Biblioteka",
    "Gabinet osobliwości",
    "Garderoba",
    "Komnata medytacyjna",
    "Krypta",
    "Kuchnia",
    "Kuźnia",
    "Loch",
    "Łazienka",
    "Magazyn komponentów",
    "Obserwatorium astrologiczne",
    "Pokoje sług",
    "Pokój gościnny",
    "Pracownia alchemiczna",
    "Pracownia jubilerska",
    "Sala operacyjna",
    "Sala przywołań",
    "Warsztat",
    "Zbrojownia"
  ]
};

// Wieże: anomalie
export const wiezeAnomalie = {
  type: "picker",
  list: [
    "Dywany zmieniające wzory",
    "Gapiące się obrazy",
    "Kot chodzący po suficie",
    "Krwawiące ściany",
    "Lewitujące przedmioty",
    "Nieskończone klepsydry",
    "Nieumarłe karaluchy",
    "Okna pokazujące inne światy",
    "Permanentne pajęczyny",
    "Płomienie rzucające ciecie",
    "Rośliny łaszące się jak koty",
    "Samogrające instrumenty",
    "Samopiszące się księgi",
    "Tajemnicze szepty",
    "Tańczące światła",
    "Wędrujące meble",
    "Wieczne przeciągi",
    "Zapach morskiej bryzy",
    "Zatrzaskujące się drzwi",
    "Zegary chodzące wspak"
  ]
};

// Wieże: skrytki
export const wiezeSkrytki = {
  type: "picker",
  list: [
    "Między książkami",
    "Pod dywanem",
    "Pod kafelkiem",
    "Pod parapetem",
    "W beczce",
    "W czaszce",
    "W kominku",
    "W odpływie",
    "W posągu",
    "W rękawie szaty",
    "W sakwie",
    "W skrzyni",
    "W słoju szlamu",
    "W starej zbroi",
    "W żyrandolu",
    "Wewnątrz nogi mebla",
    "Wśród butelek",
    "Za obluzowaną cegłą",
    "Za obrazem",
    "Za pajęczyną"
  ]
};

// Wieże: słudzy
export const wiezeSludzy = {
  type: "picker",
  list: [
    "Adepci magii",
    "Bezduszni jaszczuroludzie",
    "Czarujące pokojówki",
    "Dwunożne kozły",
    "Dystyngowani lokaje",
    "Frywolne duszki",
    "Gnijące zombie",
    "Inteligentne szczury",
    "Lamentujące upiory",
    "Niedopłacani najemnicy",
    "Ociężałe golemy",
    "Posłuszne klony",
    "Prostoduszne ogry",
    "Przebiegli zabójcy",
    "Szantażowani jeńcy",
    "Szkaradne karły",
    "Wielkie pająki",
    "Zaklęte zbroje",
    "Złośliwe impy",
    "Znudzone kariatydy"
  ]
};

// Wieże: księgi
export const wiezeKsiegi = {
  type: "picker",
  list: [
    "Almanach Alchemika",
    "Bestiariusz Przywoływacza",
    "Demonologia dla Zuchwałych",
    "Dzielny Mały Kucyk",
    "Historia Zapomnianych Ziem",
    "Pomniejsze Kulty",
    "Portale Zapomnianych Ziem",
    "Przedwieczne Monstra",
    "Przewodnik po Agdrze",
    "Przewodnik po Erteir",
    "Przewodnik po Lusz",
    "Przewodnik po Sirag",
    "Sekrety Świata Astralnego",
    "Skarby Zapomnianych Ziem",
    "Smoki przez Wieki",
    "Tajemnice Astrologii",
    "Tajniki Nekromancji",
    "W Ogniu Pożądania",
    "Wodzowie i Zdobywcy",
    "Zmień Swoje Życie"
  ]
};

// Wieże: komponenty
export const wiezeKomponenty = {
  type: "picker",
  list: [
    "Atrament krakena",
    "Czaszka licza",
    "Jedwab ogromnego pająka",
    "Kły hydry",
    "Krew amfisbeny",
    "Kwiat drzewca",
    "Łajno katoblepasa",
    "Łapa gargulca",
    "Oko bazyliszka",
    "Pazur gryfa",
    "Pióro feniksa",
    "Róg demona",
    "Róg jednorożca",
    "Serce trolla",
    "Smocze łuski",
    "Ścięgna ogra",
    "Śluz grzyboluda",
    "Włos nimfy",
    "Włos olbrzyma",
    "Żądło mantykory"
  ]
};

// Wieże: gwiazdozbiory
export const wiezeGwiazdozbiory = {
  type: "picker",
  list: [
    "Czarnoksiężnik",
    "Giermek",
    "Heros",
    "Klejnot",
    "Król",
    "Księżniczka",
    "Miecz",
    "Okręt",
    "Rumak",
    "Smok",
    "Wieża",
    "Żółw"
  ]
};

// Wieże: znaki
export const wiezeZnaki = {
  type: "picker",
  list: [
    "Kometa",
    "Koniunkcja",
    "Narodziny gwiazdy",
    "Nowa planeta",
    "Nowy gwiazdozbiór",
    "Nowy księżyc",
    "Rozbłysk słoneczny",
    "Spadająca gwiazda",
    "Zaćmienie",
    "Zderzenie gwiazd",
    "Zgaśnięcie gwiazdy",
    "Zorza"
  ]
};

export const zgliszczaSpotkania = {
  type: "picker",
  list: [
    "Barbarzyńca przemierza zgliszcza",
    "Barbarzyńcy dobijają rannych",
    "Barbarzyńcy dzielą łupy",
    "Barbarzyńcy opijają zwycięstwo",
    "Barbarzyńcy rozbijają obóz",
    "Barbarzyńcy szukają okazji do bitki",
    "Drużyna zabłądziła na losowe pole przyległe do docelowego",
    "Dziecko błąka się wśród zgliszczy",
    "Ludzie wołają o pomoc z płonącego budynku",
    "Ludzie wychodzą z kryjówki pod zgliszczami",
    "Maruderzy ukrywają łupy",
    "Potwór goni grupkę barbarzyńców",
    "Potwór kona wśród zgliszczy",
    "Potwór liże rany umierającego człowieka",
    "Potwór pożera zwłoki",
    "Stado potworów osacza rannego żołnierza",
    "Starzec śpiewa wśród zgliszczy",
    "Wieśniak przeczesuje zgliszcza",
    "Wojownik dogorywa wśród zgliszczy",
    "Żałobnicy grzebią zmarłych"
  ]
};

export const zgliszczaOdkrycia = {
  type: "picker",
  list: [
    "Kilka świeżych, płytkich grobów",
    "Kilku martwych maruderów",
    "Krater",
    "Nietknięta piwnica pod zniszczonym domem",
    "Nietknięty stos pogrzebowy",
    "Niewielkie ruiny",
    "Ogryzione kości wielkiego potwora",
    "Porzucony oręż barbarzyńskiej produkcji",
    "Pozostałości po uczcie barbarzyńców",
    "Spalony dom",
    "Spalony las",
    "Splądrowany obóz barbarzyńców",
    "Sterta trupów",
    "Ślady stadka potworów",
    "Świeżo rozstawiony obóz barbarzyńców",
    "Ukrzyżowany zdrajca",
    "Zatamowany strumień",
    "Zatrute źródło",
    "Zmasakrowane szczątki",
    "Zrujnowana świątynia"
  ]
};

export const zgliszczaNiepokojeNocne = {
  type: "picker",
  list: [
    "Banshee opłakuje zniszczenia",
    "Dwa potwory walczą o poszarpane truchło",
    "Dziecko błąka się w poszukiwaniu rodziców",
    "Eksplozja wśród zgliszczy",
    "Kapłan odprawia rytuały pogrzebowe",
    "Najeźdźcy wracają dokończyć dzieła zniszczenia",
    "Padlinożerne potwory przybyły ucztować",
    "Pijackie śpiewy maruderów",
    "Płacz żałobników",
    "Pogoda gwałtownie się pogarsza",
    "Pożar wśród zgliszczy",
    "Przybywa spóźniona odsiecz",
    "Skrzydlate potwory kołują w powietrzu",
    "Spłoszone zwierzę domowe",
    "Trupy zaczynają powstawać z martwych",
    "Ujadanie psów",
    "Walą się resztki ściany",
    "Wdowa opłakuje śmierć męża",
    "Załamany człowiek szuka pocieszenia",
    "Zdruzgotany najeźdźca szuka odkupienia"
  ]
};

export const zgliszczaSkrytki = {
  type: "picker",
  list: [
    "Na nadpalonym dachu",
    "Pod gzymsem",
    "Pod nadpaloną belką",
    "Pod przewróconą taczką",
    "Pod przewróconym płotem",
    "Pod stosem szmat",
    "W dziurawej beczce",
    "W dziurawym kotle",
    "W kupce gnatów",
    "W pękniętym kuble",
    "W płytkim grobie",
    "W podartym worku",
    "W rozbitej skrzyni",
    "W rozbitym dzbanie",
    "W starym kufrze",
    "W stercie gruzu",
    "W stercie paszy",
    "W stratowanym ogrodzie",
    "W studni",
    "W zniszczonym wozie"
  ]
};

export const zgliszczaPrzechodnie = {
  type: "picker",
  list: [
    "Dezerter",
    "Drwal",
    "Goniec",
    "Grabarz",
    "Hiena cmentarna",
    "Kanibal",
    "Kapłan",
    "Kupiec",
    "Kupiec",
    "Maruder",
    "Murarz",
    "Okultysta",
    "Partyzant",
    "Pasterz",
    "Rolnik",
    "Rolnik",
    "Szabrownik",
    "Urzędnik",
    "Zwiadowca",
    "Żołnierz"
  ]
};

export const hordaSludzyMrokmora = {
  type: "picker",
  list: [
    "Alchemik: szata, maska, kwas/olej/trujący gaz/pioruny w butelkach",
    "Berserk: skórznia, żelazne pazury, przemiana w zwierzoluda",
    "Czarownik: szata, maska, kostur/nóż/zwój",
    "Jeździec: kolczuga, włócznia, łuk, tarcza, koń/dzik/byk/jaszczur",
    "Łupieżca: skórznia, hełm, topór/miecz/pałka, worek",
    "Niewolnik: łachmany, nóż/pałka",
    "Okultysta: szaty, nóż, amulet/zwój/kadzielnica/kropidło",
    "Osiłek: skórznia, hełm, młot/maczuga/cep/dwurak/berdysz/kastety",
    "Poborca podatków: szata, sztylet/laska, mnóstwo pieniędzy, obstawa",
    "Podpalacz: skórznia, maska, pochodnie, olej/smoła, arkan/łańcuch/hak",
    "Poganiacz: skórznia, hełm, bicz",
    "Poskramiacz: skórznia, hełm, bicz/sieć/arkan, wytresowane zwierzę",
    "Rębacz: kolczuga, tarcza, hełm, topór/miecz/morgenstern",
    "Smoczy adept: szata, maska, nóż, zieje wybranym żywiołem",
    "Smoczy syn: zbroja łuskowa, hełm, dwurak/berdysz/włócznia, peleryna",
    "Smoczy wybraniec: zbroja łuskowa, tarcza, hełm i topór/miecz/morgenstern",
    "Strzelec: kolczuga, hełm, miecz, łuk/proca/oszczepy",
    "Urzędnik: szata, sztylet/laska, zwój, pomniejsza ochrona",
    "Włócznik: kolczuga, hełm, tarcza, włócznia/trójząb/halabarda",
    "Zwiadowca: skórznia, hełm, nóż, proca"
  ]
};

export const hordaPlemiona = {
  type: "picker",
  list: [
    "Plemię Burzowego Młota",
    "Plemię Czarnej Dłoni",
    "Plemię Czarnych Cierni",
    "Plemię Czerwonych Kruków",
    "Plemię Kamiennych Serc",
    "Plemię Krwawej Pięści",
    "Plemię Milczącej Gwiazdy",
    "Plemię Niebieskich Wilków",
    "Plemię Płonącej Stali",
    "Plemię Spijaczy Posoki",
    "Plemię Splątanych Rogów",
    "Plemię Stalowych Orłów",
    "Plemię Szarych Serc",
    "Plemię Topora",
    "Plemię Wężowych Uszu",
    "Plemię Wyjącego Pnia",
    "Plemię Zatrutych Serc",
    "Plemię Zgniataczy Czaszek",
    "Plemię Zjadaczy Skał",
    "Plemię Złamanego Kła"
  ]
};

export const hordaKlany = {
  type: "picker",
  list: [
    "Klan Bliznosercych",
    "Klan Gnatożujów",
    "Klan Hardodzielnych",
    "Klan Krzywonogich",
    "Klan Kwasożłopów",
    "Klan Łamikarków",
    "Klan Miażdżyczaszek",
    "Klan Mieczogryzów",
    "Klan Niedźwiedziouchych",
    "Klan Ogniowłosych",
    "Klan Panterookich",
    "Klan Sinowłosych",
    "Klan Smokobójców",
    "Klan Stalomiotów",
    "Klan Wężosercych",
    "Klan Wilkojadów",
    "Klan Wyrwidębów",
    "Klan Żarogębych",
    "Klan Żebrołamów",
    "Klan Żelaznorękich"
  ]
};

export const hordaPlotki = {
  type: "picker",
  list: [
    "[Imię] miał sen, w którym horda rusza za morze",
    "[Imię] pokonał stu wojowników w jednej bitwie",
    "[Imię] wierzy, że pokonałby Mrokmora w zapasach",
    "Astrologowie przepowiedzieli, że dobra passa wkrótce się skończy",
    "Coraz więcej maruderów zostaje w tyle",
    "Czarnoksiężnicy nie mają honoru",
    "Horda przyjmuje ochotników w swe szeregi",
    "Horda zużywa więcej zasobów, niż jest w stanie zagrabić w okolicy",
    "Jeden z hersztów uciekł z bezcennym artefaktem",
    "Mrokmor jest śmiertelnie chory",
    "Mrokmor ma siłę wszystkich swoich przodków",
    "Mrokmor potrafi petryfikować wzrokiem",
    "Mrokmor został wykuty z żelaza, które spadło z nieba",
    "Nie wszyscy członkowie hordy są wierni Mrokmorowi",
    "O świcie mają ściąć złapanego dezertera",
    "Poskramiaczom udało się okiełznać straszliwego potwora",
    "Próbowano otruć żonę Mrokmora",
    "Szeregi hordy mają zasilić górscy giganci",
    "W szeregach hordy szerzy się nieznana wcześniej plaga",
    "Wieczorem mają ukrzyżować pojmanego szpiega"
  ]
};

// Potwory: generator
export const potworyGenerator = {
  type: "picker",
  list: [
    "Chimera: ciało lwa/konia/byka/kozła, ogon węża/skorpiona, głowa człowieka/lwa/orła/barana",
    "Chimera: ciało lwa/konia/byka/kozła, ogon węża/skorpiona, skrzydła ptaka/nietoperza, głowa człowieka/lwa/orła/barana",
    "Duch: człowieka/zwierzęcia/rośliny/potwora/dżinn/demon",
    "Gargulec: granitowy/marmurowy/spiżowy/żelazny, skrzydła ptaka/nietoperza",
    "Golem: granitowy/marmurowy/spiżowy/żelazny, misterny/toporny",
    "Insekt: wielki pająk/skorpion/stonoga/osa/mrówka/komar, 2k100 nóg, żądło osy/skorpiona",
    "Jaszczur: Ciało węża/krokodyla/żółwia, 1k10 głów, 0-2 łap",
    "Jaszczur: Ciało węża/krokodyla/żółwia, 1k3 głów, 2k2 łap, skrzydła nietoperza/ważki/ptaka",
    "Jaszczur: Ciało węża/krokodyla/żółwia, 2k6 głów, 2k12 łap, 1k2 ogonów",
    "Małpa: mała/średnia/wielka, biała/brązowa/czarna, 2k2 rąk",
    "Olbrzym: 1k2 głów, 1k3 oczu, 1k100 rąk, 1k10×3 metrów wzrostu",
    "Olbrzym: 1k2 głów, 1k3 oczu, 1k3 rogów, 2k4 rąk, 3k3 metrów wzrostu",
    "Ptak: granitowy/elektryczny/ognisty/organiczny, rozpiętość skrzydeł 1k8×3 metry",
    "Rój: malutkich insektów/gryzoni/ptaków/nietoperzy/gadów/ryb",
    "Ryba: rekin/płaszczka/węgorz/żabnica, wodna/piaskowa/powietrzna",
    "Zwierzolud: cztery nogi i łeb kozła/barana/konia/byka/orła/lwa, reszta ludzka",
    "Zwierzolud: cztery nogi kozła/barana/konia/byka/orła/lwa, reszta ludzka",
    "Zwierzolud: dwie nogi i łeb kozła/barana/konia/byka/orła/lwa, reszta ludzka",
    "Zwierzolud: dwie nogi kozła/barana/konia/byka/orła/lwa, reszta ludzka",
    "Zwierzolud: łeb kozła/barana/konia/byka/orła/lwa, reszta ludzka",
  ],
};

// Bożki: imiona
export const bozkiImiona = {
  type: "picker",
  list: [
    "Ctha-Sotha",
    "Cthee-Shogtha",
    "Cthoa-Ynarth",
    "Dhothanophk",
    "Fthulhyopha",
    "Ghoa-Nianith",
    "Nith-Shotha",
    "Oleth",
    "Rle-Lloigua",
    "Sha-Nthloiga",
    "Shuulmellyu",
    "Ub-Tanoth",
    "Ub-Yurath",
    "Vhluuhgorath",
    "Voorm-Llacha",
    "Yathoniath",
    "Yoleh",
    "Yuhothoath",
    "Zathyopha",
    "Zothee",
    "Bithonil",
    "Ctha-Hanteg",
    "Cthothoa",
    "Dlyehothu",
    "Fthoa-Azath",
    "Gnigg-Shadrath",
    "Gnyogthadrakh",
    "Nianosha",
    "Shoa-Shanyarl",
    "Thuddithu",
    "Turatha",
    "Ub-Yekur",
    "Ubboth",
    "Uhg-Anath",
    "Ulhub",
    "Ulhubboth",
    "Ulm-Urath",
    "Ur-Ulzscharth",
    "Voormitha",
    "Yigosh",
  ],
};

// Bożki: domeny
export const bozkiDomeny = {
  type: "picker",
  list: [
    "Blizny",
    "Błoto",
    "Brzytwy",
    "Gnaty",
    "Gwiazdy",
    "Kajdany",
    "Kły",
    "Kolce",
    "Kwas",
    "Lawa",
    "Mgła",
    "Pleśń",
    "Popiół",
    "Posoka",
    "Rogi",
    "Ropuchy",
    "Ruiny",
    "Szlam",
    "Sztylety",
    "Ślepota",
    "Bruk",
    "Chwasty",
    "Groby",
    "Grzyby",
    "Gwoździe",
    "Mosty",
    "Narkotyki",
    "Padlina",
    "Pijawki",
    "Robactwo",
    "Rozczarowania",
    "Sępy",
    "Szczury",
    "Śmieci",
    "Tatuaże",
    "Wandale",
    "Węgorze",
    "Węże",
    "Wodorosty",
    "Złoto",
  ],
};

// Przedmioty: codziennego użytku
export const przedmiotyCodziennegoUzytku = {
  type: "picker",
  list: [
    "Buty",
    "Dywan",
    "Kaptur",
    "Kostur",
    "Koszula",
    "Kufel",
    "Lina",
    "Lira",
    "Osełka",
    "Pas",
    "Peleryna",
    "Pióro do pisania",
    "Piszczałka",
    "Rękawice",
    "Sakwa",
    "Spodnie",
    "Spódnica",
    "Stalowe kulki",
    "Suknia",
    "Szata",
  ],
};

// Przedmioty: broń i zbroje
export const przedmiotyBronIZbroje = {
  type: "picker",
  list: [
    "Buty/nagolenniki",
    "Długi/dwuręczny miecz",
    "Hełm",
    "Kastet/pazury",
    "Krótki/długi łuk",
    "Lekka/ciężka kusza",
    "Młot/kafar",
    "Morgenstern/korbacz",
    "Napierśnik/kolczuga",
    "Proca/oszczep",
    "Rękawice/karwasze",
    "Róg myśliwski",
    "Siodło",
    "Skórznia/przeszywanica",
    "Szabla/katana",
    "Sztandar/totem",
    "Sztylet/krótki miecz",
    "Tarcza/puklerz",
    "Topór/berdysz",
    "Włócznia/trójząb",
  ],
};

export const przedmiotyKosztownosci = {
  type: "picker",
  list: [
    "Berło",
    "Bransoletka",
    "Diadem",
    "Figurka",
    "Guz (ozdobny guzik)",
    "Kielich",
    "Kielich",
    "Kolczyki",
    "Korona",
    "Łańcuszek",
    "Maska",
    "Naszyjnik",
    "Obrączka",
    "Pierścień",
    "Pozytywka",
    "Przycisk do papieru",
    "Sztabka",
    "Świecznik",
    "Torkwes",
    "Waza"
  ]
};

export const przedmiotyMaterialy = {
  type: "picker",
  list: [
    "Dzieło starożytnych",
    "Misternie grawerowane",
    "Platynowe",
    "Srebrne",
    "Wysadzane klejnotami",
    "Z adamantium",
    "Z drogocennego marmuru",
    "Z egzotycznego drewna",
    "Z elektrum",
    "Z gwiezdnego metalu",
    "Z jednego kawałka kryształu",
    "Z kolorowego szkła",
    "Z kości straszliwego potwora",
    "Z masy perłowej",
    "Z mitrilu",
    "Z obsydianu",
    "Z orichalcum",
    "Z porcelany",
    "Z rzadkiego koralu",
    "Złote"
  ]
};

export const przedmiotyZaklete = {
  type: "picker",
  list: [
    "Chodzenie po ścianach",
    "Chodzenie po wodzie",
    "Codziennie tworzy 1 monetę",
    "Gadający przedmiot",
    "Krótkodystansowe loty",
    "Niewidzialność na bezdechu",
    "Odstrasza robactwo",
    "Pozwala rozkazywać golemowi",
    "Przenośna dziura",
    "Przywołanie pomniejszego potwora",
    "Wyzwala błyskawicę w linii prostej",
    "Wyzwala deszcz kwasu",
    "Wyzwala falę wody",
    "Wyzwala kłęby duszącego gazu",
    "Wyzwala kulę ognia",
    "Wyzwala podmuch wiatru",
    "Wyzwala stożek lodu",
    "Wyzwala toczący się głaz",
    "Zamienia wodę w wino",
    "Zawraca pociski do strzelca"
  ]
};

export const przedmiotyPrzeklete = {
  type: "picker",
  list: [
    "Bezwładne nogi",
    "Bezwładne ręce",
    "Brak odbicia",
    "Burzowa chmurka nad głową",
    "Daltonizm",
    "Hałasowanie przy każdym ruchu",
    "Kamienny sen przez 8 godzin",
    "Kompletne wyłysienie",
    "Mówienie wspak",
    "Obrośnięcie czarnym futrem",
    "Okrutny rozstrój żołądka",
    "Ośle uszy",
    "Przyciąganie komarów",
    "Przyciąganie piorunów",
    "Przyciąganie potworów",
    "Straszliwe koszmary senne",
    "Tracenie 1k6 złota co godzinę",
    "Upijanie się każdą cieczą",
    "Włosy na języku i zębach",
    "Zamiana w żabę"
  ]
};

export const przedmiotyNapitki = {
  type: "picker",
  list: [
    "Ciemne piwo Specjalność Agdry (10%)",
    "Czaj barbarzyńców",
    "Destylat przodków (95%)",
    "Dobry rocznik wina z Lusz (15%)",
    "Grzaniec korzenny (10%)",
    "Kumys Wilczych Jeźdźców (5%)",
    "Lokalne piwo (5%)",
    "Lokalne wino owocowe (10%)",
    "Miód generalski z Sirag (15%)",
    "Miód gryczany z Sirag (10%)",
    "Mleko",
    "Napar kwiatowy",
    "Napar ziołowy",
    "Rosół z kaczki/kury/gołębia/gęsi",
    "Sławny cydr z Erteir (5%)",
    "Sok z lasu (jagody, jeżyny, maliny, poziomki itp.)",
    "Sok z sadu (jabłka, gruszki, wiśnie, brzoskwinie itp.)",
    "Wino gronowe Krew Lusz (10%)",
    "Woda",
    "Wywar z czarnych orzechów"
  ]
};

export const przedmiotyJednorazowe = {
  type: "picker",
  list: [
    "Lek (do krwi) – zasklepia rany",
    "Lek (do oka) – zdejmuje klątwy",
    "Lek (do płuc) – zwalcza choroby",
    "Lek (do żołądka) – zwalcza trucizny",
    "Narkotyk (do krwi) – łagodny pobudzacz, uzależnia po 3k6 dawkach",
    "Narkotyk (do krwi) – silny pobudzacz, uzależnia po 1k6 dawkach",
    "Narkotyk (do płuc) – łagodny rozluźniacz, uzależnia po 3k6 dawkach",
    "Narkotyk (do płuc) – silny rozluźniacz, uzależnia po 1k6 dawkach",
    "Narkotyk (do żołądka) – łagodny halucynogen, uzależnia po 3k6 dawkach",
    "Narkotyk (do żołądka) – silny halucynogen, uzależnia po 1k6 dawkach",
    "Niematerialność przez 1k6 minut",
    "Niewidzialność przez 1k6 minut",
    "Trucizna (do krwi) – wyniszcza",
    "Trucizna (do krwi) – zabija",
    "Trucizna (do płuc) – wyniszcza",
    "Trucizna (do płuc) – zabija",
    "Trucizna (do żołądka) – wyniszcza",
    "Trucizna (do żołądka) – zabija",
    "Widzenie w ciemnościach przez 1k6 minut",
    "Żywioł w butelce"
  ]
};

export const pomyslyNaPostacie = {
  type: "picker",
  list: [
  "Cwany przemytnik",
  "Cyniczny łowca nagród",
  "Dobrotliwy łowca",
  "Egoistyczny włamywacz",
  "Honorowy najemnik",
  "Jarmarczny siłacz",
  "Jowialny zbójca",
  "Nastoletni kieszonkowiec",
  "Nieczuły lichwiarz",
  "Nieokrzesany barbarzyńca",
  "Odważny podróżnik",
  "Pedantyczny skryba",
  "Pobożny pielgrzym",
  "Poważny cyrulik",
  "Przedsiębiorczy kupiec",
  "Strachliwy kartograf",
  "Szlachetny rycerz",
  "Towarzyski muzykant",
  "Wyrywny wykidajło",
  "Zaradny szewc",
  ],
  };
  
  export const przykladoweDruzyny = {
  type: "picker",
  list: [
  "Banda barbarzyńców",
  "Banda rabusiów",
  "Grupa czeladników",
  "Grupa myśliwych",
  "Karawana kupiecka",
  "Kolegium czarnoksiężników",
  "Krąg druidów",
  "Niesławni banici",
  "Oddział zwiadowców",
  "Orszak arystokraty",
  "Paczka żaków",
  "Pielgrzymka pokutników",
  "Rodzina pionierów",
  "Trupa cyrkowa",
  "Wataha wilkołaków",
  "Wianuszek adoratorów",
  "Wyprawa badawcza",
  "Wyprawa misyjna",
  "Załoga rozbitków",
  "Zbiegli niewolnicy",
  ],
  };
  
  export const przykladoweMotywacje = {
  type: "picker",
  list: [
  "Dokonać zemsty",
  "Dowieść swojej odwagi",
  "Napić się w spokoju piwa",
  "Obalić tyrana",
  "Odkryć zaginioną cywilizację",
  "Odpokutować za grzechy",
  "Polec w chwale",
  "Stworzyć mapę okolicy",
  "Uratować świat",
  "Wyzwolić niewolników",
  "Zdobyć bogactwo",
  "Zdobyć legendarny artefakt",
  "Zdobyć miłość",
  "Zdobyć potęgę",
  "Zdobyć sławę",
  "Zdobyć władzę",
  "Zgładzić Mrokmora",
  "Zgładzić straszliwą bestię",
  "Zgromadzić armię",
  "Zwiedzić świat",
  ],
  };
  
  export const przykladoweMiejscaStartu = {
  type: "picker",
  list: [
  "Błądzicie po bagnach (1,8)",
  "Obozujecie w dziczy (6,4)",
  "Płyniecie rzeką (8,4)",
  "Podróżujecie na południe (1,1)",
  "Podróżujecie na północ (16,9)",
  "Podróżujecie na wschód (1,10)",
  "Podróżujecie na zachód (16,1)",
  "Przemierzacie równiny (14,3)",
  "Przeprawiacie się przez góry (14,6)",
  "Przeszliście przez portal (15,2)",
  "Przeszliście przez portal (2,9)",
  "Spotykacie się w karczmie w Agdrze (7,6, Dzielnica Przybyszów)",
  "Spotykacie się w karczmie w Erteir (10,3, Dzielnica Przybyszów)",
  "Spotykacie się w karczmie w Lusz (1,5, Dzielnica Przybyszów)",
  "Spotykacie się w karczmie w Sirag (12,9, Dzielnica Przybyszów)",
  "Stoicie na rozstajach (3,5)",
  "Wędrujecie traktem (11,7)",
  "Wkraczacie do podziemi (4,2)",
  "Wyruszacie z wieży Venghasta (12,4)",
  "Wyruszacie z wieży Żółtej Wiedźmy (2,9)",
  ],
  };




// export const dziczSpotkania = {
//   type: "picker",
//   list: [
//   ],
// };
